# Generated by Django 2.1 on 2018-08-17 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(blank=True, help_text='enter the first name of user', max_length=100, null=True)),
                ('license_no', models.CharField(blank=True, help_text='enter the last name', max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, help_text='enter the contact', null=True)),
                ('institution_bus_no', models.CharField(blank=True, help_text='enter the username', max_length=100, null=True)),
                ('registration_no', models.CharField(blank=True, help_text='enter the username', max_length=100, null=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.IntegerField(blank=True, help_text='enter the contact', null=True),
        ),
    ]
