# Generated by Django 2.1 on 2018-08-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180817_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdata',
            name='creation_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='driverdata',
            name='last_modified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
