# Generated by Django 2.1 on 2018-08-18 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180818_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdata',
            old_name='first_name',
            new_name='bus_no',
        ),
        migrations.RenameField(
            model_name='driverdata',
            old_name='password',
            new_name='bus_reg_no',
        ),
        migrations.RenameField(
            model_name='driverdata',
            old_name='address',
            new_name='license_no',
        ),
        migrations.RemoveField(
            model_name='driverdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='driverdata',
            name='last_name',
        ),
    ]
