# Generated by Django 2.1 on 2018-08-20 10:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_auto_20180820_1003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DriverData',
            new_name='NotaPro',
        ),
    ]
