# Generated by Django 2.1 on 2018-08-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180820_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notapro',
            name='address',
        ),
        migrations.RemoveField(
            model_name='notapro',
            name='email',
        ),
        migrations.RemoveField(
            model_name='notapro',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='notapro',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='notapro',
            name='password',
        ),
    ]
