# Generated by Django 2.1 on 2018-08-20 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_auto_20180820_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='enter the address', max_length=300, null=True)),
                ('contact', models.IntegerField(blank=True, help_text='enter the contact', null=True)),
                ('username', models.CharField(blank=True, help_text='enter the username', max_length=100, null=True)),
                ('password', models.CharField(blank=True, help_text='enter the strong password', max_length=100, null=True)),
                ('creation_date', models.DateTimeField(editable=False, null=True)),
                ('last_modified', models.DateTimeField(editable=False, null=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='notapro',
            name='author',
        ),
        migrations.DeleteModel(
            name='NotaPro',
        ),
    ]
