# Generated by Django 2.1 on 2018-08-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_auto_20180820_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driverdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, help_text='enter the bus driver name', max_length=100, null=True)),
                ('bus_no', models.CharField(blank=True, help_text='enter the bus number', max_length=100, null=True)),
                ('license_no', models.CharField(blank=True, help_text='enter the license number', max_length=300, null=True)),
                ('contact', models.IntegerField(blank=True, help_text='enter the contact', null=True)),
                ('bus_reg_no', models.CharField(blank=True, help_text='enter the bus register number', max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='author',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
